name: Auto Deploy to Vultr
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Copy files to Vultr server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VULTR_IP }}
          username: ${{ secrets.VULTR_USER }}
          key: ${{ secrets.VULTR_SSH_KEY }}
          source: "."
          target: ${{ secrets.APP_PATH }}

      - name: Restart VerzekBot service
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VULTR_IP }}
          username: ${{ secrets.VULTR_USER }}
          key: ${{ secrets.VULTR_SSH_KEY }}
          script: |
            cd /opt/VerzekAutoTrader
            systemctl restart verzekbot
