name: Auto Deploy to Vultr

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Copy files to Vultr via SSH
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.VULTR_IP }}
          username: ${{ secrets.VULTR_USER }}
          key: ${{ secrets.VULTR_SSH_KEY }}
          source: "."
          target: ${{ secrets.APP_PATH }}

      - name: Restart VerzekBot service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VULTR_IP }}
          username: ${{ secrets.VULTR_USER }}
          key: ${{ secrets.VULTR_SSH_KEY }}
          script: |
            cd ${{ secrets.APP_PATH }}
            source venv/bin/activate
            pkill -f main.py || true
            nohup python3 main.py > logs.txt 2>&1 &